"""Reframe Paper 5 as an AI-methodology paper with formal analysis."""
from pathlib import Path

path = Path(__file__).resolve().parents[1] / "artifacts/paper5_trace_guard/full_run/deliverables/paper_final_corrected.md"
text = path.read_text(encoding="utf-8")

start = text.index("### Threat model and design requirements")
end = text.index("### Prespecified conditions")
theory = r'''### Problem formulation

Let $X\in\mathcal{X}$ denote a baseline clinical record and $Y\in\{0,1\}$ the subsequently joined bleeding outcome. The goal is not to learn a parameter vector from the 86 observations. Instead, a frozen language model implements a scoring functional $G:\mathcal{S}\rightarrow[0,1]\times\{0,1\}$ on a serialized state space $\mathcal{S}$. A compiler $C_A$ maps the source record into a state card $S=C_A(X)$ using a prespecified allow-list $A$. The generator returns a probability-like score $P$ and a generator abstention flag $A_G$.

The methodological problem is to evaluate $G\circ C_A$ while ensuring that $Y$ cannot influence $S$, the prompt, or the committed score. Write $\sigma(Z)$ for the information generated by random variable $Z$. The desired outcome-blindness condition is

$$
\sigma(S,T_c)\subseteq\sigma(X_A),\qquad Y\notin X_A,
$$

where $T_c$ is the fixed template for condition $c$. This is a computational information-flow constraint, not a claim that the foundation model has never encountered related concepts during pretraining. In the implementation it is operationalized by deterministic projection onto $A$ and by committing the inference event before $Y$ is joined.

For patient $i$ and condition $c$, the generator produces

$$
G(S_i,T_c)=(P_{ic},A^G_{ic},R_{ic}),
$$

where $P_{ic}\in[0,1]\cup\{\bot\}$, $A^G_{ic}\in\{0,1\}$, and $R_{ic}$ is a rationale. The symbol $\bot$ represents a missing numerical output caused by refusal, parsing failure, null output, or exhausted retries. Importantly, $\bot$ is not mapped to a probability. This preserves the distinction between model uncertainty and computational failure.

### Generator–critic composition

In the complete method, a role-separated critic $Q$ evaluates the state card and generator proposal:

$$
Q(S_i,P_{ic},R_{ic})=(U_{ic},F_{ic},Z_{ic}),
$$

where $U_{ic}$ is acceptance, $F_{ic}$ is forced abstention, and $Z_{ic}$ is a critique. Generator and critic were separate MiniMax-M3 calls with different instructions; therefore $Q$ should be interpreted as prompted self-critique rather than a statistically independent model.

The release rule is a selective prediction function

$$
D_{ic}=\mathbb{1}(P_{ic}\neq\bot)\,(1-A^G_{ic})\,(1-F_{ic})\,U_{ic},
$$

and the system releases $P_{ic}$ only when $D_{ic}=1$. Equivalently, final abstention is

$$
A_{ic}=1-D_{ic}=A^G_{ic}\lor F_{ic}\lor(1-U_{ic})\lor\mathbb{1}(P_{ic}=\bot).
$$

This conjunctive release rule has a precise implication. If $g=\Pr(A^G=0,P\neq\bot)$, $f=\Pr(F=0\mid A^G=0,P\neq\bot)$, and $u=\Pr(U=1\mid F=0,A^G=0,P\neq\bot)$, then operational coverage is

$$
\kappa=\Pr(D=1)=gfu.
$$

Thus each safety gate can only decrease coverage, and moderate rejection at several gates compounds multiplicatively. Without assuming independence, the elementary bound

$$
\kappa\leq\min\{g,\Pr(F=0),\Pr(U=1),\Pr(P\neq\bot)\}
$$

still holds. This explains why an apparently reasonable critic acceptance count need not yield useful operational coverage.

### Selective-risk objective

A probability model with abstention should not be optimized or evaluated by discrimination alone. Let $\ell(P,Y)$ be a proper scoring loss, here the Brier loss $(P-Y)^2$. For a release rule $D$, define coverage and selective risk as

$$
\kappa(D)=\mathbb{E}[D],\qquad
\mathcal{R}_{\mathrm{sel}}(D)=\frac{\mathbb{E}[D\,\ell(P,Y)]}{\mathbb{E}[D]},
$$

provided $\kappa(D)>0$. The degenerate rule $D\equiv0$ can avoid every observed error but has undefined selective risk and zero utility. Consequently, a meaningful design problem is constrained optimization,

$$
\min_D\ \mathcal{R}_{\mathrm{sel}}(D)
\quad\text{subject to}\quad \kappa(D)\geq\kappa_{\min},
$$

where $\kappa_{\min}$ is fixed before outcome inspection. FullAuditedAgent violates every positive coverage constraint because $\hat\kappa=0$. It cannot be called safe-and-effective merely because it releases no erroneous prediction.

In finite samples, analytical score coverage and release coverage must be separated:

$$
\widehat\kappa_{\mathrm{score}}=\frac{1}{n}\sum_{i=1}^{n}\mathbb{1}(P_i\neq\bot),\qquad
\widehat\kappa_{\mathrm{release}}=\frac{1}{n}\sum_{i=1}^{n}D_i.
$$

For FullAuditedAgent these quantities were $73/86$ and $0/86$, respectively. AUROC and AUPRC describe the first subset; operational utility depends on the second.

### Calibration decomposition

The Brier score is

$$
\mathrm{BS}=\frac{1}{m}\sum_{i:P_i\neq\bot}(P_i-Y_i)^2.
$$

For grouped predictions, it can be decomposed conceptually into uncertainty, resolution, and reliability. If bin $b$ contains $n_b$ observations, mean prediction $\bar p_b$, event fraction $\bar y_b$, and overall event fraction $\bar y$, then

$$
\mathrm{BS}=\bar y(1-\bar y)
-\sum_b\frac{n_b}{m}(\bar y_b-\bar y)^2
+\sum_b\frac{n_b}{m}(\bar p_b-\bar y_b)^2.
$$

The final term is empirical reliability error. The reported expected calibration error is the corresponding absolute-loss summary,

$$
\mathrm{ECE}=\sum_b\frac{n_b}{m}\left|\bar p_b-\bar y_b\right|.
$$

Because some bins contain very few observations, ECE is a descriptive statistic rather than a stable population estimate. Nevertheless, values from 0.415 to 0.595 are too large to justify interpreting raw LLM outputs as clinical probabilities.

### Discrimination under selective missingness

For scored positive and negative observations, AUROC admits the pairwise interpretation

$$
\mathrm{AUROC}=\Pr(P^+>P^-)+\tfrac12\Pr(P^+=P^-).
$$

When $P=\bot$ depends on the record, the reported quantity is conditional:

$$
\mathrm{AUROC}_{\mathrm{obs}}
=\Pr(P^+>P^-\mid P^+\neq\bot,P^-\neq\bot).
$$

It equals full-cohort discrimination only under assumptions about the missing-score mechanism. Condition-dependent API failures violate the basis for treating the five AUROCs as paired estimates on an identical population. The analysis therefore reports confidence intervals and avoids formal superiority claims.

### Proposition: outcome-join invariance

**Proposition 1.** Suppose $C_A$ is deterministic, $Y\notin A$, prompt $T_c$ is fixed before evaluation, and the event $E_{ic}$ is committed before the outcome table is accessible. Then changing the outcome vector $Y$ while holding source predictors $X_A$ fixed cannot change the committed state-card hash or generator request for any patient.

**Proof.** The state card is $S_i=C_A(X_{i,A})$ and contains no function of $Y$. Canonical serialization and SHA-256 are deterministic, hence $H(S_i)$ is invariant to $Y$. The request is a deterministic composition of $T_c$ and $S_i$, so its serialized representation is also invariant. Because commitment precedes outcome access, no downstream join can alter the already committed request. This establishes computational outcome-join invariance. It does not establish independence from latent outcome surrogates already present in $X_A$. $\square$

### Proposition: critic monotonicity in coverage

**Proposition 2.** For a fixed set of generator outputs, adding the conjunctive critic gate cannot increase release coverage.

**Proof.** Without the critic, release indicator is $D_0=\mathbb{1}(P\neq\bot)(1-A^G)$. With the critic, $D_1=D_0(1-F)U$. Since $(1-F)U\in\{0,1\}$, $D_1\leq D_0$ pointwise. Taking expectations gives $\kappa(D_1)\leq\kappa(D_0)$. Equality holds only if every otherwise releasable prediction is accepted and not force-abstained. $\square$

The proposition shows that a critic requires a compensating benefit—lower selective loss, better calibration, or fewer unsafe releases—to justify its coverage cost. This pilot could not measure such benefit at the release level because complete abstention made selective risk undefined.

### Computational complexity

State-card construction is $O(n|A|)$ for $n$ records and $|A|$ allowed fields. Direct conditions require $n$ generator calls. FullAuditedAgent requires up to $2n$ successful calls plus retries, so API latency dominates local computation. Storage is $O(nk)$ for $k$ conditions because each condition–record event is retained. The cryptographic operations are linear in serialized message length and negligible relative to remote inference. These properties make the method feasible for retrospective evaluation, although cost and latency scale linearly with cohort size.

### Detailed algorithm framework

![Figure 1. Detailed TRACE-Guard Clinical algorithm framework. The dashed vertical boundary separates the outcome-blind inference plane from the evaluation plane.](trace_guard_algorithm_framework.png)

Figure 1 formalizes the complete data and decision path. On the inference plane, each source record is projected through the frozen allow-list before serialization; the resulting state card, condition identifier, and pre-request hash define the immutable input to the language model. The condition router changes only the prompt template and component activation, thereby realizing the five prespecified ablations without fitting cohort-specific parameters. The generator emits $(P,A^G,R)$, after which schema validation maps irrecoverable failures to $P=\bot$ rather than inventing a numerical score. In the complete arm, the critic supplies $(U,F,Z)$ and the conjunctive gate computes $D=\mathbb{1}(P\neq\bot)(1-A^G)(1-F)U$. Thus generation coverage, critic non-rejection, and critic acceptance are distinguishable algorithmic events rather than a single missingness indicator.

The write-ahead event is the interface between the two planes. Only after the request, response, gate decision, and their hashes have been committed is $Y$ attached by the unique condition--record key. The evaluation plane consequently estimates two different denominators: score coverage from $P\neq\bot$ and release coverage from $D=1$. Discrimination and calibration are computed on available scores, whereas selective risk is defined only on released scores. The bottom row of the figure summarizes the three formal consequences proved above: outcome-join invariance, pointwise critic monotonicity in coverage, and the need for a positive minimum-coverage constraint to exclude the vacuous all-abstain solution.

'''
text = text[:start] + theory + text[end:]

# Remove implementation-centric subsection while retaining the statistical section.
start = text.index("### Implementation and corrective rerun")
end = text.index("### Statistical analysis")
text = text[:start] + text[end:]

# Replace system/governance discussion subsections with theoretical interpretation.
start = text.index("### Implications for medical-informatics system design")
end = text.index("## Limitations")
discussion = r'''### Theoretical interpretation of the empirical operating points

The five conditions can be regarded as observations of a multi-objective algorithm rather than contestants in a single-metric leaderboard. Let

$$
J_c(\lambda_1,\lambda_2,\lambda_3)
=\mathrm{BS}_c+\lambda_1(1-\kappa_{\mathrm{score},c})
+\lambda_2(1-\kappa_{\mathrm{release},c})
+\lambda_3 L_c,
$$

where $L_c$ is normalized latency and the non-negative $\lambda$ values encode an application's tolerance for failure, abstention, and delay. No condition uniformly dominates for every choice of weights. NoAbstention reduces coverage penalties but has high calibration loss; FullAuditedAgent improves ECE relative to the other conditions but incurs the maximum release penalty. The preferred operating point is therefore policy-dependent and cannot be selected from AUROC alone.

The critic may be understood as a learned acceptance function $U=q(S,P,R)$ composed with a generator. If $q$ is not calibrated against a reference standard for unsafe output, increasing critic strictness changes the release distribution without guaranteeing lower clinical risk. The proper empirical object is a risk–coverage curve obtained by varying a prespecified critic threshold. A single threshold, as used here, identifies only one point. Complete abstention locates that point at the boundary $\kappa=0$, where clinical utility is zero and selective risk cannot be estimated.

The outcome-blindness proposition clarifies what the method does and does not guarantee. It prevents the evaluation outcome table from changing the request after the predictor contract is frozen. It cannot remove unmeasured temporal leakage in source fields, and it cannot prevent a pretrained model from using general epidemiological priors. Consequently, outcome blindness is necessary for valid retrospective evaluation but insufficient for causal or prospective validity.

### Identifiability and sample-size boundary

The experiment estimates several conditional quantities from at most 16 events. Let $M_c=\mathbb{1}(P_c\neq\bot)$ denote score availability. The observed score distribution identifies $\Pr(P_c,Y\mid M_c=1)$, not $\Pr(P_c,Y)$, unless assumptions are made about $M_c$. Because error rates vary by condition, missingness cannot be assumed comparable. This is why the condition differences are reported descriptively.

The critic's error-detection ability is also not identifiable from bleeding outcomes. A critic acceptance is a judgment about the validity of a generated assessment, whereas $Y$ is a patient outcome. Evaluating critic sensitivity and specificity requires a separate annotation target, such as clinician-adjudicated factual or reasoning errors. The 33 acceptances among 73 calls measure critic behavior, not critic accuracy.

Similarly, better ECE in FullAuditedAgent cannot be attributed causally to the critic because AUROC and calibration were computed on generated probabilities before applying final release, and the corrected condition came from a later rerun. A future factorial experiment with synchronized calls, common scored cases, and a prespecified critic threshold is required for component attribution.

### Methodological consequences

Three conclusions follow from the formal analysis. First, an LLM clinical-risk method is a selective stochastic service, so its estimand must include score availability and release coverage. Second, safety gating creates a constrained optimization problem; zero coverage is not an acceptable optimum. Third, evaluation-table outcome blindness can be proven at the computational workflow level even when model internals remain inaccessible. These properties distinguish the method from conventional supervised prediction and motivate reporting standards tailored to API-based clinical algorithms.

Future experiments should estimate risk–coverage curves, calibrate critic thresholds on data separate from final validation, and define clinician-labelled audit errors. Repeated API calls are needed to separate cohort uncertainty from model-service variability. A larger temporally separated cohort would permit paired condition analysis on common successful cases, calibration curves with adequate bin counts, and comparison with clinical and parsimonious statistical baselines. Until then, TRACE-Guard should be interpreted as a formally specified evaluation method with a documented negative operating point.

'''
text = text[:start] + discussion + text[end:]
path.write_text(text, encoding="utf-8")
print(path)
